spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/abc
    username: root
    password: pushkar2196
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true